import type { IncomingMessage, ServerResponse } from "node:http";
import { createHmac, randomBytes, scryptSync, timingSafeEqual } from "node:crypto";
import { db, partnerAccountsTable, partnerClaimCodesTable, partnerEarningsTable, posboxDevicesAttributionTable, posboxDevicesTable } from "../core/db/index.js";
import { and, eq, isNull } from "drizzle-orm";
const json=(r:ServerResponse,s:number,b:unknown)=>{r.writeHead(s,{"content-type":"application/json"});r.end(JSON.stringify(b));return true;};
function verify(password:string,stored:string){try{const [s,h]=stored.split(".");const got=scryptSync(password,Buffer.from(s,"base64url"),32),want=Buffer.from(h,"base64url");return got.length===want.length&&timingSafeEqual(got,want);}catch{return false;}}
function token(id:string){const raw=Buffer.from(JSON.stringify({id,exp:Date.now()+3*60*60*1000})).toString("base64url");return `${raw}.${createHmac("sha256",process.env.SESSION_SECRET??"").update(raw).digest("base64url")}`;}
export function partnerFromToken(value:string|undefined){try{if(!value)return;const [raw,mac]=value.split("."), expected=createHmac("sha256",process.env.SESSION_SECRET??"").update(raw).digest("base64url");if(!mac||mac.length!==expected.length||!timingSafeEqual(Buffer.from(mac),Buffer.from(expected)))return;const p=JSON.parse(Buffer.from(raw,"base64url").toString());return p.exp>Date.now()?p.id:undefined;}catch{return;}}
export function hashClaim(code:string){return createHmac("sha256",process.env.SESSION_SECRET??"").update(code.trim().toUpperCase()).digest("hex");}
export function newClaimCode(){return randomBytes(6).toString("base64url").toUpperCase();}
async function body(req:IncomingMessage){let x="";for await(const c of req)x+=c;return JSON.parse(x||"{}");}
function bearer(req:IncomingMessage){const h=req.headers.authorization??"";return h.startsWith("Bearer ")?h.slice(7):undefined;}
export async function partnerLogin(handle:string,password:string){const [p]=await db.select().from(partnerAccountsTable).where(eq(partnerAccountsTable.handle,handle.toLowerCase()));if(!p||!verify(password,p.passwordHash))throw Error("Invalid partner credentials");return {token:token(p.id),partner:{id:p.id,name:p.name,handle:p.handle,status:p.status}};}
export async function resolveClaim(code:string){const [c]=await db.select().from(partnerClaimCodesTable).where(and(eq(partnerClaimCodesTable.codeHash,hashClaim(code)),isNull(partnerClaimCodesTable.revokedAt)));return c;}
export async function partnerEarnings(partnerId:string){return db.select().from(partnerEarningsTable).where(eq(partnerEarningsTable.partnerId,partnerId));}
export async function handlePartnerRoute(req:IncomingMessage,res:ServerResponse,u:URL):Promise<boolean>{
 if(req.method==="POST"&&u.pathname==="/api/partner/login"){const v=await body(req);try{return json(res,200,await partnerLogin(String(v.handle??""),String(v.password??"")));}catch(e){return json(res,401,{error:e instanceof Error?e.message:"Invalid credentials"});}}
 const pid=partnerFromToken(bearer(req));
 if(req.method==="GET"&&u.pathname.match(/^\/api\/partner\/[^/]+\/earnings$/)){const id=u.pathname.split("/")[3];if(!pid||pid!==id)return json(res,401,{error:"Partner authentication required"});return json(res,200,{partnerId:id,earnings:await partnerEarnings(id)});}
 if(req.method==="POST"&&u.pathname.match(/^\/api\/partner\/[^/]+\/claim-code$/)){const id=u.pathname.split("/")[3];if(!pid||pid!==id)return json(res,401,{error:"Partner authentication required"});const code=newClaimCode();await db.update(partnerClaimCodesTable).set({revokedAt:new Date()}).where(and(eq(partnerClaimCodesTable.partnerId,id),isNull(partnerClaimCodesTable.revokedAt)));const [row]=await db.insert(partnerClaimCodesTable).values({partnerId:id,codeHash:hashClaim(code)}).returning({id:partnerClaimCodesTable.id,createdAt:partnerClaimCodesTable.createdAt});return json(res,201,{claimCode:code,...row});}
 if(req.method==="POST"&&u.pathname==="/api/posbox/devices"){const v=await body(req),mac=String(v.mac??v.macAddress??"").trim().toUpperCase(),code=String(v.claimCode??"").trim().toUpperCase();if(!/^([0-9A-F]{2}:){5}[0-9A-F]{2}$/.test(mac)||!code)return json(res,400,{error:"Valid mac and claimCode required"});const claim=await resolveClaim(code);if(!claim)return json(res,401,{error:"Invalid or revoked claim code"});const [existing]=await db.select().from(posboxDevicesAttributionTable).where(eq(posboxDevicesAttributionTable.mac,mac));if(existing&&existing.partnerId!==claim.partnerId){await db.update(posboxDevicesAttributionTable).set({conflictAlert:`MAC rebind attempted from partner ${existing.partnerId} to ${claim.partnerId}`,lastSeenAt:new Date()}).where(eq(posboxDevicesAttributionTable.id,existing.id));return json(res,409,{error:"MAC already bound to another partner",conflict:true,deviceId:existing.deviceId});}if(existing){await db.update(posboxDevicesAttributionTable).set({lastSeenAt:new Date(),conflictAlert:null}).where(eq(posboxDevicesAttributionTable.id,existing.id));return json(res,200,{deviceId:existing.deviceId,partnerId:existing.partnerId,mac});}const [device]=await db.insert(posboxDevicesTable).values({mac,claimCode:code}).returning({id:posboxDevicesTable.id});await db.insert(posboxDevicesAttributionTable).values({deviceId:device.id,partnerId:claim.partnerId,mac});return json(res,201,{deviceId:device.id,partnerId:claim.partnerId,mac});}
 return false;
}
export { verify };
